apiVersion: v1
kind: Namespace
metadata:
  name: forward
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forward-scratch
  namespace: forward
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forward-cbr-backups
  namespace: forward
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forward-cbr-restore
  namespace: forward
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi

