apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-dns
spec:
  entryPoints:
    - websecure
  tls:
    secretName: proxy-tls
  routes:
    - match: PathPrefix(`/dns`)
      kind: Rule
      priority: 250
      middlewares:
        - name: skyforge-auth
        - name: strip-dns
      services:
        - name: technitium-dns
          port: 5380
