apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
  labels:
    app: technitium-dns
spec:
  type: NodePort
  selector:
    app: technitium-dns
  ports:
    - name: web
      port: 5380
      targetPort: 5380
      nodePort: __SKYFORGE_DNS_WEB_NODEPORT__
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      nodePort: __SKYFORGE_DNS_NODEPORT__
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: __SKYFORGE_DNS_NODEPORT__
      protocol: TCP
