apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: freeradius
  name: freeradius
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: freeradius
  ports:
    - name: radius-auth
      port: 1812
      protocol: UDP
      targetPort: 1812
    - name: radius-acct
      port: 1813
      protocol: UDP
      targetPort: 1813
