apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: s3gw
  name: {{ .Values.skyforge.s3gw.serviceName }}
spec:
  ports:
    - name: s3
      port: {{ .Values.skyforge.s3gw.service.port }}
      targetPort: {{ .Values.skyforge.s3gw.service.port }}
  selector:
    app.kubernetes.io/name: s3gw
