apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: skyforge-server
  name: skyforge-server
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app.kubernetes.io/name: skyforge-server
