apiVersion: v1
kind: ConfigMap
metadata:
  name: api-docs
data:
  index.html: |
{{ .Files.Get "files/redoc/index.html" | nindent 4 }}
binaryData:
  redoc.standalone.js: {{ .Files.Get "files/redoc/redoc.standalone.js" | b64enc | quote }}
