apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dex
  template:
    metadata:
      labels:
        io.kompose.service: dex
    spec:
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.37.0
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex
              readOnly: true
      volumes:
        - name: dex-config
          secret:
            secretName: dex-config
            items:
              - key: config.yaml
                path: config.yaml
