apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dex
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - dex
            - serve
            - /etc/dex/config.yaml
          image: dexidp/dex:v2.41.1
          livenessProbe:
            httpGet:
              path: /dex/.well-known/openid-configuration
              port: 5556
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /dex/.well-known/openid-configuration
              port: 5556
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 2
          name: dex
          volumeMounts:
            - mountPath: /etc/dex
              name: dex-config
              readOnly: true
            - mountPath: /var/dex
              name: dex-data
      restartPolicy: Always
      volumes:
        - name: dex-config
          persistentVolumeClaim:
            claimName: dex-config
            readOnly: true
        - name: dex-data
          persistentVolumeClaim:
            claimName: dex-data
