apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webhooks
  name: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhooks
  template:
    metadata:
      labels:
        io.kompose.service: webhooks
    spec:
      automountServiceAccountToken: false
      containers:
        - image: skyforge-webhooks:latest
          imagePullPolicy: Always
          name: webhooks
          env:
            - name: WEBHOOKS_BASE_URL
              value: /webhooks
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - mountPath: /data
              name: webhooks-data
      restartPolicy: Always
      volumes:
        - name: webhooks-data
          persistentVolumeClaim:
            claimName: webhooks-data
