apiVersion: v1
kind: ConfigMap
metadata:
  name: skyforge-server-infra-config-worker
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  infra.config.json: |
{{- .Files.Get "files/infra.config.json" | nindent 4 }}

