apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-openapi
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  openapi.json: |
{{- .Files.Get "files/swagger-openapi.json" | nindent 4 }}
